# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-18 22:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0008_auto_20151110_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='board',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
