# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-09 23:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0016_auto_20170609_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='committee',
            name='description',
            field=models.CharField(max_length=500),
        ),
    ]
