# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-04 17:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0017_auto_20170404_1314'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Family',
            new_name='DuesPayment',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='family',
            new_name='dues_payment',
        ),
    ]
