# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-04 15:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0018_auto_20170404_1343'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='dues_payment',
        ),
        migrations.AddField(
            model_name='member',
            name='dues_payments',
            field=models.ManyToManyField(to='membership.DuesPayment'),
        ),
    ]
